global_vars:
    data_dir: "<<PATH_TO_DATA_DIR>>"
    species: "Homo sapiens" # don't modify
    overwrite: False

workflows:
    downloading_pathway_data:
        name: "downloading_pathway_data.qmd"
        title: "CPR: Downloading Pathway Data"
        species_specific: False
        connect_id: 
        artifacts:
            bigg_sbml_dir: "bigg_sbmls"
            bigg_sbml_dfs: "bigg_sbml_dfs.pickle"
            reactome_sbml_dfs: "reactome_sbml_dfs.pickle"
            reactome_sbml_dir: "reactome_sbmls"
            intact_dir: "intact"
            intact_sbml_dfs: "intact_sbml_dfs.pickle"
            string_aliases: "string_aliases.txt"
            string_interactions: "string_interactions.txt"
            string_sbml_dfs: "string_sbml_dfs.pickle"
            trrust_sbml_dfs: "trrust_sbml_dfs.pickle"
            trrust_raw: "trrust.csv"

    understanding_sbml_dfs:
        name: "understanding_sbml_dfs.qmd"
        title: "CPR: Understanding the SBML DFs Pathway Format"
        species_specific: False
        connect_id: 
        artifacts:
            sbml_dfs: "test_pathway/sbml_dfs.pkl"

    merging_models_into_a_consensus:
        name: "merging_models_into_a_consensus.qmd"
        title: "CPR: Merging Pathway Models into a Consensus"
        species_specific: False
        connect_id: 
        artifacts:

    formatting_sbml_dfs_as_cpr_graphs:
        name: "formatting_sbml_dfs_as_cpr_graphs.qmd"
        title: "CPR: Formatting sbml_dfs as cpr_graphs"
        species_specific: False
        connect_id: 
        artifacts:
            sbml_dfs: "test_pathway/sbml_dfs.pkl"

    suggesting_mechanisms_with_networks:
        name: "suggesting_mechanisms_with_networks.qmd"
        title: "CPR: Suggesting Mechanisms with Networks"
        species_specific: False
        connect_id: 
        artifacts:
            sbml_dfs: "test_pathway/sbml_dfs.pkl"
            cpr_graph: "test_pathway/regulatory_graph.pkl"

    working_with_genome_scale_pathways:
        name: "working_with_genome_scale_pathways.qmd"
        title: "CPR: Working with Genome-Scale Pathways"
        species_specific: False
        connect_id: 
        artifacts:
            sbml_dfs: "test_pathway/sbml_dfs.pkl"

    adding_data_to_graphs:
        name: "adding_data_to_graphs.qmd"
        title: "CPR: Adding Data to Graphs"
        species_specific: False
        connect_id: 
        artifacts:
